### ISSUE TITLE
How should I paste OpenAI API key?

### ISSUE THREAD

**Issue by khabaroff** [b-yp/logseq-ai-auto-tags#1]
Is there any example? Thank you

**Comment by b-yp** [comment]
Hello, the service I'm using here is not OpenAI's API but rather: https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Nlks5zkzu. You don't need to set up an API key yourself. The previous issue with non-functionality was due to the token expiration. I've updated the code; please update the plugin for use.

**Comment by b-yp** [comment]
https://github.com/b-yp/logseq-ai-auto-tags/pull/2

**Comment by khabaroff** [comment]
Thank you for update!
