### ISSUE TITLE
是否能够支持递归读取当前 block 下所有的子节点内容再分析得出标签？

### ISSUE THREAD

**Issue by x1nchen** [b-yp/logseq-ai-auto-tags#4]
RT，因为我这边大部分场景下 block 都是标题，真正的内容在子节点上

**Comment by b-yp** [comment]
可以支持的哈， 今天我这边还有点事， 明天晚上之前搞好。

**Comment by x1nchen** [comment]
Take your time, there's no need to make any promises.  ^_^

**Comment by b-yp** [comment]
Done： https://github.com/b-yp/logseq-ai-auto-tags/commit/02cb2330b272d2429e8b56587b6eb8c511bfd0bd

**Comment by x1nchen** [comment]
Good job, thanx~
